### ISSUE TITLE
大佬为啥一直不答题一直循环

### ISSUE THREAD

**Issue by oobo4** [KirigiriSuzumiya/XueXiTong_web#11]
![3](https://user-images.githubusercontent.com/102136608/167235494-12c7d264-7fb6-4712-a2a1-19dba03ad975.PNG)

**Comment by oobo4** [comment]
![捕获](https://user-images.githubusercontent.com/102136608/167235544-1a5cea8b-3edc-4019-a07a-69b3511f37e4.PNG)
这样了不知为啥

**Comment by KirigiriSuzumiya** [comment]
你可以尝试在输入视频tag时随便打点东西（不要留空）
然后测试tag留空。

不是超星尔雅的标准课程样式不保证能用的
要兼容你学校老师自己搞的课程请自己修改代码。
