### ISSUE TITLE
大佬还是不行

### ISSUE THREAD

**Issue by oobo4** [KirigiriSuzumiya/XueXiTong_web#13]
![捕获](https://user-images.githubusercontent.com/102136608/167251380-a52813ef-cc7a-4f65-ba8c-7cf2f166543f.PNG)

**Comment by KirigiriSuzumiya** [comment]
你看下readme好不好
一键做题是要填有题目页面的url

**Comment by oobo4** [comment]
![捕获](https://user-images.githubusercontent.com/102136608/167253910-67117821-c390-4365-8e07-cfa30841bd31.PNG)
还是不行

**Comment by oobo4** [comment]
麻烦了大佬会了
