### ISSUE TITLE
增强功能:每隔一段时间打印当前视频时长

### ISSUE THREAD

**Issue by EarlySummer1** [KirigiriSuzumiya/XueXiTong_web#15]
该项目我跑在ubuntu服务器上，经过修改之后是可以运行的，但是没有GUI，看不到实时进度条。
```python
video_length = chrome.find_element(By.CLASS_NAME, 'vjs-duration-display').text
video_current_length = chrome.find_element(By.CLASS_NAME, 'vjs-current-time-display').text
print("开始播放视频,总时长:%s秒,当前时长:%s秒" % (video_length, video_current_length))
```
按照上面这样就可以，但是不知道加在哪里,`while True`并不会一直执行

**Comment by KirigiriSuzumiya** [comment]
我的那个while（150行）是监控播放器的那个暂停键的，视频没有暂停或完成就不会重复。
初衷是希望在windows的浏览器窗口因为鼠标不小心移入导致焦点丢失，播放暂停的时候能够自动恢复播放
linux上我不清楚视频播放会不会自动暂停。

- 如果不会的话，直接用你的代码替换我自动继续播放的代码就行。把原本的until（152行）换成你的代码再加个sleep延时
- 如果担心播放会暂停我觉得可以在我的while循环外启动一个子进程用于显示进度。并在elif（158行）处终止他
