### ISSUE TITLE
报错：未发现有弹窗题目

### ISSUE THREAD

**Issue by daifiyum** [KirigiriSuzumiya/XueXiTong_web#2]
登陆成功！
章节标题： 章节测验
未发现有弹窗题目！
[32436:34492:0503/214236.312:ERROR:device_event_log_impl.cc(214)] [21:42:36.313] USB: usb_device_handle_win.cc:1049 Failed to read descriptor from node connection: 连到系统上的设备没有发挥作用。 (0x1F)

**Comment by KirigiriSuzumiya** [comment]
是崩溃了吗，这只是一句警告日志

**Comment by daifiyum** [comment]
> 是崩溃了吗，这只是一句警告日志

运行脚本后，卡在“未发现有弹窗题目”这，不动了？

**Comment by daifiyum** [comment]
> > 是崩溃了吗，这只是一句警告日志
> 
> 运行脚本后，卡在“未发现有弹窗题目”这，不动了？

在题目页面，页面里的题目也没自动选答案

**Comment by KirigiriSuzumiya** [comment]
能看一下你的网课页面是什么样的吗，我用的都是这样的界面
![image](https://user-images.githubusercontent.com/82195326/166486643-f5421fe5-1152-4e18-a97d-08b4c483f332.png)

**Comment by lemongad** [comment]
不能答题，没有答题窗口
![Uploading IMG_20220504_001221.jpg…]()

**Comment by lemongad** [comment]
用的是那个一键运行

**Comment by lemongad** [comment]
出现了新问题
![Uploading 1651595570832.jpg…]()

**Comment by daifiyum** [comment]
> 能看一下你的网课页面是什么样的吗，我用的都是这样的界面 ![image](https://user-images.githubusercontent.com/82195326/166486643-f5421fe5-1152-4e18-a97d-08b4c483f332.png)

用的就是这样的旧版页面，执行脚本后，弹出个浏览器窗口，然后就没反应了

**Comment by daifiyum** [comment]
![屏幕截图 2022-05-04 073940.png](https://img.dnxrzl.com/2022/05/04/f9805ffecb6a0.png)
![屏幕截图 2022-05-04 073920.png](https://img.dnxrzl.com/2022/05/04/8c9eae9214c6b.png)
脚本里的URL我填了课程主页链接（第一张图链接），和章节测试页链接（第二张图链接）都不行，章节测试里的题没有自动做题，好久都没反应

**Comment by KirigiriSuzumiya** [comment]
> ![屏幕截图 2022-05-04 073940.png](https://camo.githubusercontent.com/f0e1bcfbf0137330f8a328efd3edaa9a2302e53413a09706cb22ba735d930876/68747470733a2f2f696d672e646e78727a6c2e636f6d2f323032322f30352f30342f663938303566666563623661302e706e67) ![屏幕截图 2022-05-04 073920.png](https://camo.githubusercontent.com/a1541b89f79478260ce4a3df51dc2f4a6ca16ff9a88a64c8884b1ec575204ac1/68747470733a2f2f696d672e646e78727a6c2e636f6d2f323032322f30352f30342f386339656165393231346336622e706e67) 脚本里的URL我填了课程主页链接（第一张图链接），和章节测试页链接（第二张图链接）都不行，章节测试里的题没有自动做题，好久都没反应

我尝试进行你所给页面的修复，但因为我的课程中并没有你所给的样式，所以你能够进行一下尝试

**Comment by daifiyum** [comment]
> > ![屏幕截图 2022-05-04 073940.png](https://camo.githubusercontent.com/f0e1bcfbf0137330f8a328efd3edaa9a2302e53413a09706cb22ba735d930876/68747470733a2f2f696d672e646e78727a6c2e636f6d2f323032322f30352f30342f663938303566666563623661302e706e67) ![屏幕截图 2022-05-04 073920.png](https://camo.githubusercontent.com/a1541b89f79478260ce4a3df51dc2f4a6ca16ff9a88a64c8884b1ec575204ac1/68747470733a2f2f696d672e646e78727a6c2e636f6d2f323032322f30352f30342f386339656165393231346336622e706e67) 脚本里的URL我填了课程主页链接（第一张图链接），和章节测试页链接（第二张图链接）都不行，章节测试里的题没有自动做题，好久都没反应
> 
> 我尝试进行你所给页面的修复，但因为我的课程中并没有你所给的样式，所以你能够进行一下尝试

赞啊，修复了

**Comment by KirigiriSuzumiya** [comment]
感谢反馈问题
