### ISSUE TITLE
卡在学习目标

### ISSUE THREAD

**Issue by lemongad** [KirigiriSuzumiya/XueXiTong_web#3]
![Uploading 1651596050054.jpg…]()
![Uploading 1651596079570.jpg…]()

**Comment by KirigiriSuzumiya** [comment]
你的图片好像没有上传成功，我看不到

**Comment by lemongad** [comment]
![捕获2](https://user-images.githubusercontent.com/104255899/166622471-a844c58b-340e-41f7-814f-d37904634feb.PNG)
![捕获](https://user-images.githubusercontent.com/104255899/166622481-9a6f259b-731b-4131-840d-d5579e7f2b73.PNG)
![捕获1](https://user-images.githubusercontent.com/104255899/166622489-aed65ad5-9efd-4d6b-8a23-433d91ddf80a.PNG)

**Comment by lemongad** [comment]
已经重新上传

**Comment by KirigiriSuzumiya** [comment]
> 已经重新上传

我尝试进行了修复，你可以再试试看

**Comment by lemongad** [comment]
> > 已经重新上传
> 
> 我尝试进行了修复，你可以再试试看

已尝试，正常工作，点赞
