### ISSUE TITLE
答题出现问题

### ISSUE THREAD

**Issue by lemongad** [KirigiriSuzumiya/XueXiTong_web#4]
搜索题目答案后，不能自动答上去，无法进入下一步
![屏幕截图 2022-05-04 192659](https://user-images.githubusercontent.com/104255899/166673246-44d2e789-9fb2-4f09-abc5-ff9f297152ec.png)
![屏幕截图 2022-05-04 192731](https://user-images.githubusercontent.com/104255899/166673291-85ec188f-6654-4af4-a90b-acc75eff8187.png)

**Comment by KirigiriSuzumiya** [comment]
给一下卡住的页面截图

**Comment by lemongad** [comment]
![屏幕截图 2022-05-04 214020](https://user-images.githubusercontent.com/104255899/166693779-0b0fa157-fbb4-40fa-bce3-c2aa82
![捕获](https://user-images.githubusercontent.com/104255899/166693806-ac82b24c-5653-4fb4-a7a1-06bc523d7370.PNG)
90b5f0.png)

**Comment by lemongad** [comment]
![屏幕截图 2022-05-04 214020](https://user-images.githubusercontent.com/104255899/166693925-32ff9cba-85b0-4bdb-8dfd-74353cd88bcb.png)

**Comment by KirigiriSuzumiya** [comment]
我不太清楚这是个什么问题，他确实去搜过题了吗。因为我看日志中他应该认为这是一个视频点而不是题目点。如果去搜过题应该不会提交不了

**Comment by lemongad** [comment]
这个问题大概刷五六个视频出现一次，出现频率不太稳定，等再出现这问题，才能截图

**Comment by lemongad** [comment]
这次一用就碰巧出现此问题，只答了一题，就无法进
![屏幕截图 2022-05-05 085030](https://user-images.githubusercontent.com/104255899/166849768-c98115ad-0384-47f4-beb1-8df6089f7e34.png)
行
![image](https://user-images.githubusercontent.com/104255899/166849813-3e3f74f2-1173-4458-946f-cf855c58b4ca.png)
![image](https://user-images.githubusercontent.com/104255899/166849837-c9546000-d211-45c7-a64d-b0426c980406.png)
![image](https://user-images.githubusercontent.com/104255899/166849847-7bd479a9-279a-4331-a920-4566e09e15e2.png)
![image](https://user-images.githubusercontent.com/104255899/166849859-43a99358-7ebc-4590-baec-ae2eb3292576.png)

**Comment by lemongad** [comment]
这个章节每次进入都会卡在这里，我是手动答题，再运行程序，才可跳过卡住

**Comment by lemongad** [comment]
发现跳过那个章节后，下一个章节也出现了一模一样的状况

**Comment by lemongad** [comment]
仔细察看，发现中间多搜了一道没有的题目，
![image](https://user-images.githubusercontent.com/104255899/166851749-61615da4-67e8-4fad-b92b-e6dfe0d6a8c5.png)
![image](https://user-images.githubusercontent.com/104255899/166851757-b0284244-3e96-40ca-bd2d-2f5789c11d2c.png)

**Comment by KirigiriSuzumiya** [comment]
翻看一下日志应该有一个作业id：XXXXX 课程id：XXXX
把这两个id填入下面的地址
https://mooc1.chaoxing.com/api/selectWorkQuestion?workId=作业id&courseId=课程id
看一下这个网页中是否有多出的题目
