### ISSUE TITLE
一直开在界面不答题

### ISSUE THREAD

**Issue by PrayingDream** [KirigiriSuzumiya/XueXiTong_web#6]
![屏幕截图](https://user-images.githubusercontent.com/92030029/167053990-78c18c3a-23f5-4131-8843-d85fbbf94a6c.png)

**Comment by PrayingDream** [comment]
就在这个界面 不断地刷新  不进入测试界面

**Comment by KirigiriSuzumiya** [comment]
错误原因是
![image](https://user-images.githubusercontent.com/82195326/167058164-bd7460af-790e-4c51-810e-ea2d1c037cc7.png)
而我设计的界面是
![image](https://user-images.githubusercontent.com/82195326/167058330-63eb6fc0-bdcb-4a59-8248-679cbb9933e5.png)
现在已经有很多人告诉我这个标签的数量和标签中的内容各不相同
我考虑添加一个事前输入让大家自定义这个标签的内容
稍后我会发布这个更新

**Comment by PrayingDream** [comment]
ok  感谢

**Comment by KirigiriSuzumiya** [comment]
> ok 感谢

你可以进行一下尝试，我自己的课程都刷完了，没法试，很尴尬
