### ISSUE TITLE
为啥是这样的

### ISSUE THREAD

**Issue by oobo4** [KirigiriSuzumiya/XueXiTong_web#9]
![捕获](https://user-images.githubusercontent.com/102136608/167111868-37c3c23f-f783-4cb3-9e57-43c829fac9cc.PNG)

**Comment by KirigiriSuzumiya** [comment]
另外，你这个课应该是学校自己导入的课吧，有许多不符合格式的多任务点。不是超星泛雅通识课我这个不一定能用
